name: Build Pico Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Pico Firmware
      uses: SomethingWithComputers/pico-build-action@v1
      with:
        platform: 'rp2040'
        board: 'pico'

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pico-serprog-release
        path: |
          **/*.uf2
